// ============================================
// Sprix EdTech — Project Data Model
// ============================================

// Default portfolios (can be edited/extended by user)
const DEFAULT_PORTFOLIOS = [
    { id: 'national', name: 'National Assessments', icon: '🏛️', color: '#6366f1' },
    { id: 'partner', name: 'Partner Assessments', icon: '🤝', color: '#06b6d4' },
    { id: 'platform', name: 'Platform & Engineering', icon: '💻', color: '#8b5cf6' },
    { id: 'content', name: 'Content & Publishing', icon: '📚', color: '#f59e0b' },
    { id: 'monetization', name: 'Monetization', icon: '💰', color: '#22c55e' },
    { id: 'operations', name: 'Operations & Governance', icon: '🛡️', color: '#3b82f6' },
    { id: 'people', name: 'People & Org', icon: '👥', color: '#ec4899' }
];

// Available icons for portfolio selection
const PORTFOLIO_ICON_OPTIONS = [
    '🏛️', '🤝', '💻', '📚', '💰', '🛡️', '👥', '🌐',
    '🚀', '⚡', '🏆', '🎯', '📈', '🏗️', '📣', '📋',
    '❤️', '🧭', '🔬', '📊'
];

const PORTFOLIO_COLOR_OPTIONS = [
    '#6366f1', '#06b6d4', '#8b5cf6', '#f59e0b', '#22c55e',
    '#3b82f6', '#ec4899', '#ef4444', '#14b8a6', '#f97316'
];

let PORTFOLIOS = [];
const STATUS_LIST = ['Not Started', 'On Track', 'At Risk', 'Off Track', 'Done'];
const STATUS_CLASSES = { 'Not Started': 'not-started', 'On Track': 'on-track', 'At Risk': 'at-risk', 'Off Track': 'off-track', 'Done': 'done' };
const STATUS_COLORS = { 'Not Started': '#94a3b8', 'On Track': '#22c55e', 'At Risk': '#f59e0b', 'Off Track': '#ef4444', 'Done': '#6366f1' };

const APPROVAL_STEPS = ['Draft', 'Review', 'Approved', 'Submitted', 'Accepted'];
const APPROVAL_CLASSES = ['draft', 'review', 'approved', 'submitted', 'accepted'];

const PROJECTS = [
    // --- National Assessments ---
    { id: 1, portfolio: 'national', name: 'TOFAS Math (MoE)', objective: 'National math assessment for MoE schools', owner: 'Ahmed K.', accountable: 'Tanaka-san', stakeholders: ['MoE', 'HQ'], status: 'On Track', progress: 72, startDate: '2025-09-01', targetDate: '2026-04-15', deliverables: 'Assessment results report, Score dashboards', currentFocus: 'Grading pipeline optimization', blockers: '', risks: 'Data latency during peak scoring', nextMilestone: 'Term 2 results release', lastUpdated: '2026-02-28', approvalFlow: 'Approved', deliverableType: 'Report', version: 'v3', submissionDate: '2026-03-10', acceptanceResult: '', releaseVersion: '', dependency: '', dataSpecReady: 'Yes', qaReady: 'Yes', incidentLog: '' },
    { id: 2, portfolio: 'national', name: 'TOFAS Programming (MoE)', objective: 'National programming assessment rollout', owner: 'Ahmed K.', accountable: 'Tanaka-san', stakeholders: ['MoE', 'HQ'], status: 'At Risk', progress: 45, startDate: '2025-10-01', targetDate: '2026-05-20', deliverables: 'Programming test platform, Results analytics', currentFocus: 'Test environment stability', blockers: 'MoE server capacity approval pending', risks: 'Concurrent user load exceeds 50k', nextMilestone: 'Pilot test with 5 schools', lastUpdated: '2026-02-27', approvalFlow: 'Review', deliverableType: 'Data sheet', version: 'v2', submissionDate: '', acceptanceResult: '', releaseVersion: 'v1.2', dependency: 'Infrastructure', dataSpecReady: 'Yes', qaReady: 'No', incidentLog: '' },
    { id: 3, portfolio: 'national', name: 'Al-Azhar Assessment', objective: 'Assessment implementation for Al-Azhar schools', owner: 'Mohamed S.', accountable: 'Suzuki-san', stakeholders: ['Al-Azhar', 'HQ'], status: 'Not Started', progress: 10, startDate: '2026-01-15', targetDate: '2026-06-30', deliverables: 'Implementation plan, Pilot report', currentFocus: 'Stakeholder alignment meetings', blockers: 'Al-Azhar approval for pilot scope', risks: 'Different curriculum structure', nextMilestone: 'MoU signing', lastUpdated: '2026-02-25', approvalFlow: 'Draft', deliverableType: 'Contract', version: 'v1', submissionDate: '', acceptanceResult: '', releaseVersion: '', dependency: '', dataSpecReady: 'No', qaReady: 'No', incidentLog: '' },
    // --- Partner Assessments ---
    { id: 4, portfolio: 'partner', name: 'EJS TOFAS Programming', objective: 'Partner assessment data sharing & analysis', owner: 'Fatma A.', accountable: 'Tanaka-san', stakeholders: ['EJS', 'HQ'], status: 'On Track', progress: 60, startDate: '2025-11-01', targetDate: '2026-04-30', deliverables: 'Data sheets, Analysis reports', currentFocus: 'Data format standardization', blockers: '', risks: 'EJS data format incompatibility', nextMilestone: 'Q1 data delivery', lastUpdated: '2026-02-28', approvalFlow: 'Approved', deliverableType: 'Data sheet', version: 'v2', submissionDate: '2026-03-05', acceptanceResult: '', releaseVersion: '', dependency: 'Data Pipeline', dataSpecReady: 'Yes', qaReady: 'Yes', incidentLog: '' },
    { id: 5, portfolio: 'partner', name: 'KSA/Alhussan Retake Ops', objective: 'Manage retake scheduling and operations for KSA', owner: 'Layla M.', accountable: 'Suzuki-san', stakeholders: ['KSA', 'Alhussan', 'HQ'], status: 'At Risk', progress: 35, startDate: '2026-01-01', targetDate: '2026-03-31', deliverables: 'Retake schedule, Code issuance log, Backup policy', currentFocus: 'Retake date coordination with Alhussan', blockers: 'Awaiting KSA retake eligibility criteria', risks: 'Result deletion policy not finalized', nextMilestone: 'Retake window opens', lastUpdated: '2026-02-26', approvalFlow: 'Review', deliverableType: 'Report', version: 'v1', submissionDate: '', acceptanceResult: '', releaseVersion: '', dependency: '', dataSpecReady: 'No', qaReady: 'No', incidentLog: 'Previous results backup incomplete' },
    // --- Platform & Engineering ---
    { id: 6, portfolio: 'platform', name: 'MoE Portal / Dashboard', objective: 'Build MoE admin portal with analytics dashboard', owner: 'Omar H.', accountable: 'Yamamoto-san', stakeholders: ['MoE', 'HQ'], status: 'On Track', progress: 68, startDate: '2025-08-01', targetDate: '2026-04-01', deliverables: 'Portal v2, Dashboard widgets, User guide', currentFocus: 'Dashboard performance optimization', blockers: '', risks: 'API rate limits under heavy load', nextMilestone: 'Dashboard v2 beta release', lastUpdated: '2026-02-28', approvalFlow: 'Approved', deliverableType: 'Website', version: 'v2.1', submissionDate: '2026-03-15', acceptanceResult: '', releaseVersion: 'v2.1-beta', dependency: 'Data Pipeline', dataSpecReady: 'Yes', qaReady: 'Yes', incidentLog: '' },
    { id: 7, portfolio: 'platform', name: 'SPL Development', objective: 'Internal operations support tools', owner: 'Omar H.', accountable: 'Yamamoto-san', stakeholders: ['HQ', 'Egypt Ops'], status: 'On Track', progress: 55, startDate: '2025-10-01', targetDate: '2026-05-30', deliverables: 'Data sync module, Template engine, Permission system', currentFocus: 'Template engine development', blockers: '', risks: 'Scope creep from new feature requests', nextMilestone: 'Data sync module release', lastUpdated: '2026-02-27', approvalFlow: 'Review', deliverableType: 'Report', version: 'v1.3', submissionDate: '', acceptanceResult: '', releaseVersion: 'v1.3', dependency: 'Infrastructure', dataSpecReady: 'Yes', qaReady: 'No', incidentLog: '' },
    { id: 8, portfolio: 'platform', name: 'Payments Integration', objective: 'Paymob/Instapay payment integration', owner: 'Karim T.', accountable: 'Yamamoto-san', stakeholders: ['HQ', 'Paymob'], status: 'Off Track', progress: 25, startDate: '2025-12-01', targetDate: '2026-03-15', deliverables: 'Payment gateway, Certificate download flow', currentFocus: 'Paymob API integration debugging', blockers: 'Paymob sandbox credentials expired', risks: 'PCI compliance requirements unclear', nextMilestone: 'Payment flow demo', lastUpdated: '2026-02-28', approvalFlow: 'Draft', deliverableType: 'Report', version: 'v1', submissionDate: '', acceptanceResult: '', releaseVersion: 'v0.5', dependency: 'MoE Portal', dataSpecReady: 'No', qaReady: 'No', incidentLog: 'Sandbox timeout 2026-02-15' },
    { id: 9, portfolio: 'platform', name: 'Data Pipeline', objective: 'ID templates, result data, analysis pipeline', owner: 'Sara E.', accountable: 'Yamamoto-san', stakeholders: ['HQ', 'MoE'], status: 'On Track', progress: 70, startDate: '2025-09-15', targetDate: '2026-04-15', deliverables: 'ETL pipeline, Data validation rules, Analysis templates', currentFocus: 'Concept-level results aggregation', blockers: '', risks: 'Data quality from field collection', nextMilestone: 'Pipeline v2 deployment', lastUpdated: '2026-02-28', approvalFlow: 'Approved', deliverableType: 'Data sheet', version: 'v2', submissionDate: '2026-03-01', acceptanceResult: '', releaseVersion: 'v2.0', dependency: '', dataSpecReady: 'Yes', qaReady: 'Yes', incidentLog: '' },
    { id: 10, portfolio: 'platform', name: 'Infrastructure & Security', objective: 'Load handling, WAF, monitoring, incident response', owner: 'Karim T.', accountable: 'Yamamoto-san', stakeholders: ['HQ'], status: 'At Risk', progress: 50, startDate: '2025-07-01', targetDate: '2026-06-30', deliverables: 'WAF config, Monitoring dashboards, Incident playbook', currentFocus: 'WAF rule optimization', blockers: 'Basic Auth removal timeline from MoE', risks: 'DDoS vulnerability during exam periods', nextMilestone: 'WAF deployment complete', lastUpdated: '2026-02-26', approvalFlow: 'Review', deliverableType: 'Report', version: 'v1', submissionDate: '', acceptanceResult: '', releaseVersion: '', dependency: '', dataSpecReady: 'Yes', qaReady: 'No', incidentLog: 'WAF false positive 2026-02-10' },
    // --- Content & Publishing ---
    { id: 11, portfolio: 'content', name: 'Textbooks: Math', objective: 'Math textbook Term1/2 split, index & cover updates', owner: 'Nour R.', accountable: 'Sato-san', stakeholders: ['HQ', 'MoE'], status: 'On Track', progress: 80, startDate: '2025-06-01', targetDate: '2026-03-20', deliverables: 'Math Term1 book, Math Term2 book, Index v3', currentFocus: 'Final proofreading Term 2', blockers: '', risks: 'Printing deadline pressure', nextMilestone: 'Term 2 to printer', lastUpdated: '2026-02-28', approvalFlow: 'Submitted', deliverableType: 'Chapter', version: 'v3', submissionDate: '2026-02-28', acceptanceResult: '', releaseVersion: '', dependency: '', dataSpecReady: '', qaReady: '', incidentLog: '' },
    { id: 12, portfolio: 'content', name: 'Textbooks: Programming', objective: 'Programming textbook development', owner: 'Nour R.', accountable: 'Sato-san', stakeholders: ['HQ'], status: 'On Track', progress: 65, startDate: '2025-08-01', targetDate: '2026-04-15', deliverables: 'Programming textbook, Exercise bank', currentFocus: 'Chapter 8-10 drafting', blockers: '', risks: 'Technical review bottleneck', nextMilestone: 'Draft complete', lastUpdated: '2026-02-27', approvalFlow: 'Review', deliverableType: 'Chapter', version: 'v2', submissionDate: '', acceptanceResult: '', releaseVersion: '', dependency: '', dataSpecReady: '', qaReady: '', incidentLog: '' },
    { id: 13, portfolio: 'content', name: 'Textbooks: Science (G11)', objective: 'Grade 11 Science textbook — priority delivery', owner: 'Hana B.', accountable: 'Sato-san', stakeholders: ['HQ', 'MoE'], status: 'Off Track', progress: 30, startDate: '2025-11-01', targetDate: '2026-03-10', deliverables: 'Science G11 textbook, Lab manual', currentFocus: 'Responding to MoE revision requests', blockers: 'MoE requested major chapter restructuring', risks: 'Deadline at risk due to scope change', nextMilestone: 'Revised draft submission', lastUpdated: '2026-02-28', approvalFlow: 'Draft', deliverableType: 'Chapter', version: 'v1.1', submissionDate: '', acceptanceResult: 'Revision', releaseVersion: '', dependency: '', dataSpecReady: '', qaReady: '', incidentLog: '' },
    { id: 14, portfolio: 'content', name: 'Textbooks: Financial Literacy', objective: 'Financial literacy textbook creation', owner: 'Hana B.', accountable: 'Sato-san', stakeholders: ['HQ'], status: 'Not Started', progress: 5, startDate: '2026-02-01', targetDate: '2026-07-30', deliverables: 'Financial literacy textbook', currentFocus: 'Curriculum outline review', blockers: '', risks: 'New subject area — no prior template', nextMilestone: 'Outline approval', lastUpdated: '2026-02-20', approvalFlow: 'Draft', deliverableType: 'Chapter', version: 'v0.1', submissionDate: '', acceptanceResult: '', releaseVersion: '', dependency: '', dataSpecReady: '', qaReady: '', incidentLog: '' },
    { id: 15, portfolio: 'content', name: 'Weekly Assessment Test', objective: 'Design & implement weekly assessment framework', owner: 'Fatma A.', accountable: 'Sato-san', stakeholders: ['HQ', 'MoE'], status: 'On Track', progress: 55, startDate: '2025-10-01', targetDate: '2026-05-01', deliverables: 'Weekly test bank, Auto-grading templates', currentFocus: 'Question bank expansion for Term 2', blockers: '', risks: 'Question quality consistency', nextMilestone: 'Term 2 test bank complete', lastUpdated: '2026-02-27', approvalFlow: 'Approved', deliverableType: 'Report', version: 'v2', submissionDate: '2026-02-15', acceptanceResult: 'Accepted', releaseVersion: '', dependency: '', dataSpecReady: '', qaReady: '', incidentLog: '' },
    // --- Monetization ---
    { id: 16, portfolio: 'monetization', name: 'Certificate Sales', objective: 'Certificate sales at 250 EGP — MoE promo integration', owner: 'Layla M.', accountable: 'Tanaka-san', stakeholders: ['MoE', 'HQ'], status: 'On Track', progress: 75, startDate: '2025-09-01', targetDate: '2026-03-31', deliverables: 'Sales dashboard, Payment integration, Promotion materials', currentFocus: 'Launch day sales tracking setup', blockers: '', risks: 'Payment gateway reliability', nextMilestone: 'Sales launch', lastUpdated: '2026-02-28', approvalFlow: 'Approved', deliverableType: 'Report', version: 'v1', submissionDate: '2026-02-20', acceptanceResult: 'Accepted', releaseVersion: '', dependency: 'Payments', dataSpecReady: 'Yes', qaReady: 'Yes', incidentLog: '' },
    { id: 17, portfolio: 'monetization', name: 'Supplementary Books', objective: 'Post-certification learning materials sales', owner: 'Nour R.', accountable: 'Tanaka-san', stakeholders: ['HQ'], status: 'Not Started', progress: 10, startDate: '2026-02-15', targetDate: '2026-06-30', deliverables: 'Product catalog, Sales landing page', currentFocus: 'Market research for book topics', blockers: '', risks: 'Unclear demand for supplementary materials', nextMilestone: 'Product catalog draft', lastUpdated: '2026-02-22', approvalFlow: 'Draft', deliverableType: 'Report', version: 'v0.1', submissionDate: '', acceptanceResult: '', releaseVersion: '', dependency: 'Certificate Sales', dataSpecReady: '', qaReady: '', incidentLog: '' },
    { id: 18, portfolio: 'monetization', name: 'Level-based Sales Strategy', objective: 'Multi-level product bundles and pricing', owner: 'Layla M.', accountable: 'Tanaka-san', stakeholders: ['HQ'], status: 'Not Started', progress: 5, startDate: '2026-03-01', targetDate: '2026-07-31', deliverables: 'Pricing model, Bundle configuration, Sales projections', currentFocus: 'Competitor pricing analysis', blockers: '', risks: 'Price sensitivity in Egyptian market', nextMilestone: 'Pricing model proposal', lastUpdated: '2026-02-25', approvalFlow: 'Draft', deliverableType: 'Report', version: 'v0.1', submissionDate: '', acceptanceResult: '', releaseVersion: '', dependency: '', dataSpecReady: '', qaReady: '', incidentLog: '' },
    // --- Operations & Governance ---
    { id: 19, portfolio: 'operations', name: 'Project Progress Dashboard', objective: 'Internal progress management system', owner: 'Mohamed S.', accountable: 'Suzuki-san', stakeholders: ['HQ', 'Egypt Ops'], status: 'On Track', progress: 40, startDate: '2026-01-15', targetDate: '2026-04-30', deliverables: 'Web app, User documentation', currentFocus: 'MVP development', blockers: '', risks: 'Adoption resistance', nextMilestone: 'MVP launch', lastUpdated: '2026-03-01', approvalFlow: 'Review', deliverableType: 'Website', version: 'v1', submissionDate: '', acceptanceResult: '', releaseVersion: 'v0.1', dependency: '', dataSpecReady: 'Yes', qaReady: 'No', incidentLog: '' },
    { id: 20, portfolio: 'operations', name: 'Attendance / Work Tracker', objective: 'HR-visible attendance tracking for Egypt team', owner: 'Mohamed S.', accountable: 'Suzuki-san', stakeholders: ['HQ', 'HR'], status: 'Done', progress: 100, startDate: '2025-11-01', targetDate: '2026-02-28', deliverables: 'Tracker web app, Admin panel', currentFocus: 'Maintenance mode', blockers: '', risks: '', nextMilestone: 'Monthly review', lastUpdated: '2026-02-28', approvalFlow: 'Accepted', deliverableType: 'Website', version: 'v2', submissionDate: '2026-02-01', acceptanceResult: 'Accepted', releaseVersion: 'v2.0', dependency: '', dataSpecReady: 'Yes', qaReady: 'Yes', incidentLog: '' },
    { id: 21, portfolio: 'operations', name: 'Ceremony & Sponsorship', objective: 'Event site, sponsor docs, logo management', owner: 'Fatma A.', accountable: 'Suzuki-san', stakeholders: ['MoE', 'Sponsors', 'HQ'], status: 'At Risk', progress: 40, startDate: '2026-01-01', targetDate: '2026-03-20', deliverables: 'Ceremony website, Sponsor deck, Award design', currentFocus: 'Sponsor confirmation follow-ups', blockers: 'Awaiting 2 sponsor confirmations', risks: 'Venue booking conflict', nextMilestone: 'Sponsor deck finalized', lastUpdated: '2026-02-27', approvalFlow: 'Review', deliverableType: 'Website', version: 'v1', submissionDate: '', acceptanceResult: '', releaseVersion: '', dependency: '', dataSpecReady: '', qaReady: '', incidentLog: '' },
    // --- People & Org ---
    { id: 22, portfolio: 'people', name: 'Recruiting New Staff', objective: 'Hire Ops / Accounting / IT Senior roles', owner: 'Mohamed S.', accountable: 'Suzuki-san', stakeholders: ['HQ', 'HR'], status: 'On Track', progress: 50, startDate: '2026-01-01', targetDate: '2026-04-30', deliverables: 'JDs, Interview scorecards, Offer letters', currentFocus: 'IT Senior final interview round', blockers: '', risks: 'Competitive salary expectations', nextMilestone: 'IT Senior offer extension', lastUpdated: '2026-02-28', approvalFlow: 'Review', deliverableType: 'Report', version: 'v1', submissionDate: '', acceptanceResult: '', releaseVersion: '', dependency: '', dataSpecReady: '', qaReady: '', incidentLog: '' },
    { id: 23, portfolio: 'people', name: 'Salary Revision Proposal', objective: 'Team salary revision for operational strengthening', owner: 'Mohamed S.', accountable: 'Suzuki-san', stakeholders: ['HQ', 'HR'], status: 'At Risk', progress: 30, startDate: '2026-02-01', targetDate: '2026-03-31', deliverables: 'Salary benchmark report, Revision proposal', currentFocus: 'Market benchmark data collection', blockers: 'HQ budget approval timeline unclear', risks: 'Staff retention if delayed', nextMilestone: 'Benchmark report to HQ', lastUpdated: '2026-02-26', approvalFlow: 'Draft', deliverableType: 'Report', version: 'v1', submissionDate: '', acceptanceResult: '', releaseVersion: '', dependency: 'Recruiting', dataSpecReady: '', qaReady: '', incidentLog: '' }
];
