-- --------------------------------------------------------
-- Supabase Setup Script for Sprix PM
-- Copy this entire file and paste it into the Supabase SQL Editor
-- --------------------------------------------------------

-- 1. Create Portfolios Table
CREATE TABLE IF NOT EXISTS public.portfolios (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    icon TEXT,
    color TEXT
);

-- Enable Row Level Security (RLS) but make it completely public for this demo
ALTER TABLE public.portfolios ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access on portfolios" ON public.portfolios FOR SELECT USING (true);
CREATE POLICY "Allow public insert access on portfolios" ON public.portfolios FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update access on portfolios" ON public.portfolios FOR UPDATE USING (true);
CREATE POLICY "Allow public delete access on portfolios" ON public.portfolios FOR DELETE USING (true);

-- 2. Create Projects Table
CREATE TABLE IF NOT EXISTS public.projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    portfolio TEXT REFERENCES public.portfolios(id) ON DELETE SET NULL,
    status TEXT NOT NULL,
    progress INTEGER DEFAULT 0,
    owner TEXT,
    accountable TEXT,
    objective TEXT,
    currentFocus TEXT,
    blockers TEXT,
    risks TEXT,
    nextMilestone TEXT,
    targetDate DATE,
    startDate DATE,
    approvalFlow TEXT,
    lastUpdated DATE,
    stakeholders TEXT[] DEFAULT '{}',
    deliverables TEXT,
    deliverableType TEXT,
    version TEXT,
    submissionDate DATE,
    acceptanceResult TEXT,
    releaseVersion TEXT,
    dependency TEXT,
    dataSpecReady TEXT,
    qaReady TEXT,
    incidentLog TEXT
);

-- Enable RLS but make it completely public for this demo
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access on projects" ON public.projects FOR SELECT USING (true);
CREATE POLICY "Allow public insert access on projects" ON public.projects FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update access on projects" ON public.projects FOR UPDATE USING (true);
CREATE POLICY "Allow public delete access on projects" ON public.projects FOR DELETE USING (true);

-- 3. Insert Initial Data for Portfolios
INSERT INTO public.portfolios (id, name, icon, color) VALUES
    ('national', 'National Assessments', '🏛️', '#6366f1'),
    ('partner', 'Partner Assessments', '🤝', '#06b6d4'),
    ('platform', 'Platform & Engineering', '💻', '#8b5cf6'),
    ('content', 'Content & Publishing', '📚', '#f59e0b'),
    ('monetization', 'Monetization', '💰', '#22c55e'),
    ('operations', 'Operations & Governance', '🛡️', '#3b82f6'),
    ('people', 'People & Org', '👥', '#ec4899')
ON CONFLICT (id) DO NOTHING;

-- 4. Insert Initial Data for Projects
INSERT INTO public.projects (
    name, portfolio, status, progress, owner, objective, targetDate, startDate, 
    currentFocus, blockers, nextMilestone, lastUpdated, approvalFlow
) VALUES 
('TOFAS Math (MoE)', 'national', 'On Track', 72, 'Ahmed K.', 'Execute Term 2 math assessment across 5000 schools.', '2025-05-15', '2025-01-10', 'Grading pipeline optimization', NULL, 'Term 2 results release', '2025-02-20', 'Draft'),
('EJS TOFAS Programming', 'partner', 'On Track', 60, 'Fatma A.', 'Introduce programming assessment pilot to EJS network.', '2025-04-30', '2025-01-15', 'Data format standardization', NULL, 'Q1 data delivery', '2025-02-18', 'Review'),
('MoE Portal / Dashboard', 'platform', 'On Track', 68, 'Omar H.', 'Enhance national dashboard for school admins.', '2025-06-01', '2024-11-01', 'Dashboard performance optimization', NULL, 'Dashboard v2 beta', '2025-02-19', 'Approved'),
('SPL Development', 'platform', 'On Track', 55, 'Omar H.', 'Develop Sprix Platform features.', '2025-05-30', '2025-01-01', 'Template engine development', NULL, 'Data sync module', '2025-02-15', 'Draft'),
('Data Pipeline', 'platform', 'On Track', 70, 'Sara E.', 'Build robust pipeline for aggregated assessment data.', '2025-04-15', '2024-12-01', 'Concept-level results aggregation', NULL, 'Pipeline v2 deploy', '2025-02-17', 'Approved'),
('Textbooks: Math', 'content', 'On Track', 80, 'Nour R.', 'Publish localized math textbooks.', '2025-03-30', '2024-10-01', 'Final proofreading Term 2', NULL, 'Term 2 to printer', '2025-02-20', 'Review'),
('Textbooks: Programming', 'content', 'On Track', 65, 'Nour R.', 'Draft programming textbook content.', '2025-07-15', '2025-01-10', 'Chapter 8-10 drafting', NULL, 'Draft complete', '2025-02-16', 'Draft'),
('Weekly Assessment Test', 'content', 'On Track', 55, 'Fatma A.', 'Create item banks for weekly assessments.', '2025-05-01', '2025-01-05', 'Question bank expansion for Term 2', NULL, 'Term 2 test bank complete', '2025-02-14', 'Draft'),
('Certificate Sales', 'monetization', 'On Track', 75, 'Layla M.', 'Develop model for certificate sales to private schools.', '2025-03-15', '2024-11-15', 'Launch day sales tracking setup', NULL, 'Sales launch', '2025-02-19', 'Submitted'),
('Project Progress Dashboard', 'operations', 'On Track', 40, 'Mohamed S.', 'Internal dashboard for cross-team tracking.', '2025-04-20', '2025-02-01', 'MVP development', NULL, 'MVP launch', '2025-02-20', 'Draft'),
('Recruiting New Staff', 'people', 'On Track', 50, 'Mohamed S.', 'Hire 10 new engineers for platform team.', '2025-05-31', '2025-01-20', 'IT Senior final interview round', NULL, 'IT Senior offer extended', '2025-02-18', 'Draft')
;
